/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/CubeGuyCharacter.glb -o src/components/content/canvas/maps/player/Man.jsx 
*/

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import { useGraph } from '@react-three/fiber';
import { usePlayer } from './hooks/usePlayer';

export function Man({ player, position, modelIndex }) {
  const { playerRef, memoizedPosition, playerId, nodes, materials } = usePlayer(
    {
      player,
      position,
      modelIndex: modelIndex ?? player.selectedCharacterGlbNameIndex,
    },
  );

  // const playerId = player?.id;

  // const memoizedPosition = useMemo(() => position, []);

  // const playerRef = useRef(null);

  // const { scene, materials, animations } = useGLTF(
  //   `/models/CubeGuyCharacter.glb`,
  // );
  //const clone = useMemo(() => SkeletonUtils.clone(scene), []);
  //같은 모델을 사용할수도 있기 같은 동작 방지 >  깊은 복사를 통해 분리

  // useEffect(() => {
  //   console.log('scene:', scene);
  //   console.log('animations:', animations);
  // }, [scene, animations]);

  // const objectMap = useGraph(clone);
  // const nodes = objectMap.nodes;

  // const [animation, setAnimation] = useState(
  //   'CharacterArmature|CharacterArmature|CharacterArmature|Idle',
  // );

  // const { actions } = useAnimations(animations, playerRef);

  // useEffect(() => {
  //   actions[animation]?.reset().fadeIn(0.5).play();
  //   return () => {
  //     actions[animation]?.fadeOut(0.5);
  //   };
  // }, [actions, animation]);

  return (
    <group
      ref={playerRef}
      position={memoizedPosition}
      name={playerId ?? ''}
      dispose={null}
    >
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group
            name='CharacterArmature'
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name='Character'
            geometry={nodes.Character.geometry}
            material={materials.Atlas}
            skeleton={nodes.Character.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/CubeGuyCharacter.glb');
